services:
    phoenix:
        build: .
        volumes:
            - .:/app
            - _build:/app/_build
            - deps:/app/deps
        ports:
            - "4000:4000"
        depends_on:
            - db
            - minio
        env_file:
            - .env
        entrypoint: /app/entrypoint.sh
    db:
        image: postgres:12
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWD}
        restart: always
    minio:
        image: minio/minio:latest
        volumes:
            - minio_data:/minio_data
        ports:
            - "9000:9000"
        environment:
            - MINIO_ROOT_USER=${MINIO_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
        command: server /minio_data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
volumes:
    _build:
    deps:
    minio_data: